name: CI

on:
  push:
    branches: [master]
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@doctrinab'
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: npm run build --if-present
      - run: npm run unit
